on:
  schedule: 
    # runs once a week on sunday
    - cron: "50 23 * * 0"
  workflow_dispatch:
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'traffic'
    - uses: nsaunders/traffic-lite@v1
      with:
        path: traffic/traffic.json
        repo: ${{ github.repository }}
        token: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
    - uses: EndBug/add-and-commit@v9
      with:
        add: traffic/traffic.json
        default_author: github_actions
